name: check-balance

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - check-balance
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

data-files:
  - balance

executables:
  check-balance:
    main: exe/Main.hs
    dependencies:
      - check-balance

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - text
  - process
